# Generated by Django 4.2.3 on 2023-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0005_remove_user_registration_pro_pic_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='add_item_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='banner_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='edit_item_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='view_order_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='role',
            field=models.CharField(blank=True, choices=[('User1', 'User1'), ('User2', 'User2')], max_length=255, null=True),
        ),
    ]
