# Generated by Django 4.2.3 on 2023-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0006_user_registration_add_item_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_count', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('image', models.ImageField(default='static/images/default.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='add_item_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='banner_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='edit_item_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='role',
            field=models.CharField(blank=True, choices=[('user1', 'Staff'), ('user2', 'User')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='view_order_access',
            field=models.BooleanField(default=False),
        ),
    ]
