# Generated by Django 4.2.3 on 2023-07-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0007_item_alter_user_registration_add_item_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NadaliyaApp.user_registration'),
        ),
    ]
