# Generated by Django 4.2.3 on 2023-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0008_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(),
        ),
    ]
