# Generated by Django 4.2.3 on 2023-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0011_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.FileField(default='static/images/default.jpg', upload_to='images/items'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.FileField(default='static/images/default.jpg', upload_to='images/items'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.FileField(default='static/images/default.jpg', upload_to='images/items'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.FileField(default='static/images/default.jpg', upload_to='images/items'),
        ),
    ]
