# Generated by Django 4.2.3 on 2023-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NadaliyaApp', '0012_remove_item_image_item_image1_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
